# Generated by Django 5.1.6 on 2025-07-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="license_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="profile_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="specialization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="years_of_experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("tenant", "Tenant"), ("agent", "Agent"), ("admin", "Admin")],
                default="tenant",
                max_length=20,
            ),
        ),
    ]
