# Generated by Django 5.2.1 on 2025-06-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0002_feature_propertytype_remove_house_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(default="tenant", max_length=20),
        ),
    ]
