# Generated by Django 5.1.6 on 2025-07-13 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0002_agent_bio_agent_company_agent_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={
                "ordering": ["name"],
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
            },
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
            },
        ),
        migrations.AlterModelOptions(
            name="feature",
            options={
                "ordering": ["name"],
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
            },
        ),
        migrations.AlterModelOptions(
            name="house",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.AlterModelOptions(
            name="propertyimage",
            options={
                "ordering": ["house"],
                "verbose_name": "Property Image",
                "verbose_name_plural": "Property Images",
            },
        ),
        migrations.AlterModelOptions(
            name="propertytype",
            options={
                "ordering": ["name"],
                "verbose_name": "Property Type",
                "verbose_name_plural": "Property Types",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["user__username"],
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterField(
            model_name="agent",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Professional biography and description",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="company",
            field=models.CharField(
                blank=True,
                help_text="Real estate company or agency affiliation",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Contact email address", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="Professional license or registration number",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(help_text="Full name of the agent", max_length=255),
        ),
        migrations.AlterField(
            model_name="agent",
            name="phone",
            field=models.CharField(help_text="Contact phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name="agent",
            name="profile_image",
            field=models.URLField(
                blank=True, help_text="URL to the agent's profile image", null=True
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="specialization",
            field=models.CharField(
                blank=True,
                help_text="Area of specialization (e.g., residential, commercial, luxury)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="user",
            field=models.OneToOneField(
                help_text="User account associated with this agent",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="years_of_experience",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of years working as an agent"
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the property was favorited"
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="house",
            field=models.ForeignKey(
                help_text="Property that was favorited",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="realestate.house",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                help_text="User who favorited the property",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(help_text="Name of the feature", max_length=100),
        ),
        migrations.AlterField(
            model_name="house",
            name="address",
            field=models.CharField(
                help_text="Physical address of the property", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent responsible for this property",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="realestate.agent",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="area",
            field=models.PositiveIntegerField(
                default=0, help_text="Total area in square feet/meters"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="bathrooms",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of bathrooms"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="bedrooms",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of bedrooms"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the listing was created"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this property listing",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="description",
            field=models.TextField(help_text="Detailed description of the property"),
        ),
        migrations.AlterField(
            model_name="house",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                help_text="Special features of the property",
                to="realestate.feature",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="General location area (e.g., neighborhood, district)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Price in USD", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="property_status",
            field=models.CharField(
                choices=[("for_sale", "For Sale"), ("for_rent", "For Rent")],
                help_text="Whether the property is for sale or for rent",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="property_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of property (e.g., apartment, house, land)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="realestate.propertytype",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="status",
            field=models.CharField(
                default="active",
                help_text="Status of the listing (active, pending, sold, etc.)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="title",
            field=models.CharField(
                help_text="Title of the property listing", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When the listing was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="house",
            field=models.ForeignKey(
                help_text="The property this image belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="realestate.house",
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.URLField(help_text="URL to the image file"),
        ),
        migrations.AlterField(
            model_name="propertytype",
            name="name",
            field=models.CharField(
                help_text="Name of the property type", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(
                blank=True, help_text="Physical address", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="User biography or description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.URLField(
                blank=True, help_text="URL to the user's profile image", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("tenant", "Tenant"), ("agent", "Agent"), ("admin", "Admin")],
                default="tenant",
                help_text="User's role in the system",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                help_text="User account associated with this profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PropertyInquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Inquiry message from the tenant"),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, help_text="Response from the agent", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        help_text="Status of the inquiry",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the inquiry was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the inquiry was last updated"
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        help_text="Property that the inquiry is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="realestate.house",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant who made the inquiry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Inquiry",
                "verbose_name_plural": "Property Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
