# Generated by Django 5.1.6 on 2025-07-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0003_alter_agent_options_alter_favorite_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(
                help_text="Image file for the property", upload_to="property_images/"
            ),
        ),
    ]
